api:
  address: "localhost:8000"

users:
  - { username: "admin", password: "admin" }

log:
  level: info
  path: "./logs/crawlab"
  isDeletePeriodically: "N"
  deleteFrequency: "@hourly"

server:
  host: 0.0.0.0
  port: 8000
  master: "Y"
  secret: "crawlab-lite"
  register:
    # mac地址/ip地址/hostname, 如果是ip，则需要手动指定IP
    type: "mac"
    ip: ""
  lang: # 安装语言环境, Y 为安装，N 为不安装
    python: "Y"
    node: "N"
    java: "N"
    dotnet: "N"
    php: "N"

spider:
  path: "/app/spiders"

task:
  workers: 4

other:
  tmppath: "/tmp"

version: 0.0.1

setting:
  enableTutorial: "N"
  runOnMaster: "Y"
  demoSpiders: "N"
  checkScrapy: "Y"

notification:
  mail:
    server: ''
    port: ''
    senderEmail: ''
    senderIdentity: ''
    smtp:
      user: ''
      password: ''
